version: '3.7'

services:
  rabbitmq:
    image: "rabbitmq:latest"
    container_name: rabbitmq
    ports:
      - "5672:5672" # AMQP порт
      - "15672:15672" # Web-интерфейс RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      - smart-house-network
  
  inputcommandhandler:
    container_name: inputcommandhandler
    build: 
      context: ./InputCommandHandler
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet InputCommandHandler.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "InputCommandHandler.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  non-criticaldataanalysissystem:
    container_name: non-criticaldataanalysissystem
    build: 
      context: ./Non-criticalDataAnalysisSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet Non-criticalDataAnalysisSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "Non-criticalDataAnalysisSystem.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  non-criticalexternalcomponentmanagementsystem:
    container_name: non-criticalexternalcomponentmanagementsystem
    build: 
      context: ./Non-criticalExternalComponentManagementSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet Non-criticalExternalComponentManagementSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "Non-criticalExternalComponentManagementSystem.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  non-criticalexternalcomponents:
    container_name: non-criticalexternalcomponents
    build: 
      context: ./Non-criticalExternalComponents
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet Non-criticalExternalComponents.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "Non-criticalExternalComponents.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  securitymonitor:
    container_name: securitymonitor
    build: 
      context: ./SecurityMonitor
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet SecurityMonitor.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  authorizationsystem:
    container_name: authorizationsystem
    build: 
      context: ./AuthorizationSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet AuthorizationSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  criticaldataanalysissystem:
    container_name: criticaldataanalysissystem
    build: 
      context: ./CriticalDataAnalysisSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet CriticalDataAnalysisSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  criticalexternalcomponentmanagementsystem:
    container_name: criticalexternalcomponentmanagementsystem
    build: 
      context: ./CriticalExternalComponentManagementSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet CriticalExternalComponentManagementSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  criticalexternalcomponents:
    container_name: criticalexternalcomponents
    build: 
      context: ./CriticalExternalComponents
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet CriticalExternalComponents.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  criticalinputcommandprocessingsystem:
    container_name: criticalinputcommandprocessingsystem
    build: 
      context: ./CriticalInputCommandProcessingSystem
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet CriticalInputCommandProcessingSystem.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  customscriptlibrary:
    container_name: customscriptlibrary
    build: 
      context: ./CustomScriptLibrary
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet CustomScriptLibrary.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq

  systemforreadingandwritinguserscripts:
    container_name: systemforreadingandwritinguserscripts
    build: 
      context: ./SystemForReadingAndWritingUserScripts
      dockerfile: Dockerfile
    command: sh -c "sleep 30 && dotnet SystemForReadingAndWritingUserScripts.dll"
    #command: ["./wait-for-it.sh", "rabbitmq:15672", "--", "dotnet", "SecurityMonitor.dll"]
    depends_on:
      - rabbitmq
    networks:
      - smart-house-network
    links: 
      - rabbitmq
  
networks:
  smart-house-network: